[package]
name = "vm-compiler"
version = "0.1.0"
authors = ["Kevin Li <kevinli020508@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lip = "2.0.0"
im = "14.3.0"
itertools = "0.9"
lazy_static = "1.4.0"
